name: Build and Publish

on:
  - workflow_dispatch
  - workflow_call

jobs:
  test_source:
    uses: ./.github/workflows/unittest.yml

  build_wheels:
    needs: test_source
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_FREE_THREADED_SUPPORT: true
          CIBW_SKIP: "pp* *musllinux* *cp36* *cp313*"
          CIBW_ARCHS: x86_64
          CIBW_TEST_REQUIRES: "pytest parameterized"
          CIBW_TEST_COMMAND: "cd {project}/tests && pytest ."
        with:
          package-dir: ./

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_sdist:
    needs: test_source
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: make sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz

  publish_test:
    needs: [build_wheels, build_sdist]
    name: Publish package to TestPyPI
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment
    environment: release
    # https://github.com/pypa/gh-action-pypi-publish#trusted-publishing
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

  publish_prod:
    needs: [publish_test]
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
