name: Build Sphinx Docs

on:
  - pull_request
  - workflow_call

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install dependencies
        run: |
          pipx run build --sdist .
          source_file=$(ls ./dist/*.tar.gz)
          pip install ${source_file}

          pip install -r requirements/docs.txt
          cp examples/*.ipynb docs/source/examples/

      - name: Build documentation
        working-directory: ./docs
        run: make html

      - name: Upload built docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html
          path: docs/build/html
