name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.13'

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install dependencies
        run: |
          pipx run build --sdist .
          source_file=$(ls ./dist/*.tar.gz)
          pip install "${source_file}"
          pip install -r requirements/docs.txt
          cp examples/*.ipynb docs/source/examples/
          cp history.md docs/source/history.md
          cp README.md docs/source/README.md

      - name: Build documentation
        working-directory: ./docs
        run: make html

      - name: Upload built docs as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sphinx-html
          path: docs/build/html

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
